### ISSUE TITLE
libnuma.so undefined reference to `find_first'

### ISSUE THREAD

**Issue by zwt-by** [numactl/numactl#124]
I compiled libnuma.so by aarch64-linux-gnu-gcc, it goes well, but when load libnuma.so, it tells:
/opt/sysroot-aarch64/usr/lib/libnuma.so: undefined reference to `find_first'
Is there anyone help me to figure out what i did wrong?

**Comment by hbrobin** [comment]
Hi @zwt-by , please checkout version v2.0.14 and have another try.

**Comment by Sir-Ace-git** [comment]
Hey, so this is likely a bug. (ish)
I just built libnuma on an ARM64 (aarch64) platform which is fully 64-bit (no 32bit compatibility)
I built it as a prerequisite for another app which dropped the linker error above, and it turns out you need to add the path to the environment variable PKG_CONFIG_PATH

My issue with this is not that it needs to be updated, but that the directory used was a known 32 bit library directory, on a 64 bit only platform.  Something in the build needs to be updated to make sure that gets dropped in the right place.:

root@asteroid:~/HandBrake# locate numa.pc
/usr/src/done/numa.pc
/usr/src/done/numa.pc.in
/usr/local/lib/pkgconfig/numa.pc

root@asteroid:~/HandBrake# echo $PKG_CONFIG_PATH
/usr/local/lib64/pkgconfig:/usr/local/share/pkgconfig:/usr/lib64/pkgconfig:/usr/share/pkgconfig

root@asteroid:~/HandBrake# export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig

**Comment by andikleen** [comment]
I pushed a fix for this. Can you try again with the latest tree?
Thanks.

**Comment by Sir-Ace-git** [comment]
I did a fresh git clone for this, but the results were the same:



***@***.***:/usr/src/# rm -R numactl

***@***.***:/usr/src/# git clone https://github.com/numactl/numactl

***@***.***:/usr/src/# cd numactl

***@***.***:/usr/src/# ./autogen.sh

***@***.***:/usr/src/# ./configure
checking for a BSD-compatible install... /usr/bin/ginstall -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking build system type... aarch64-unknown-linux-gnu
checking host system type... aarch64-unknown-linux-gnu
checking how to print strings... printf
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert aarch64-unknown-linux-gnu file names to 
aarch64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert aarch64-unknown-linux-gnu file names to 
toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... dlltool
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... hyes
ichecking for stdint.h... syes
checking for unistd.h... tyes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions...   no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... |yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld) supports shared 
libraries... yes
checking whether -lc should be explicitly linked in... gno
checking dynamic linker characteristics... repGNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for thread local storage (TLS) class... __thread
checking whether C compiler accepts -ftree-vectorize... yes
checking for library containing __atomic_fetch_and_1...  e-latomic
xchecking that generated files are newer than configure... done
configure: creating ./config.status
port
config.status: creating Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands

***@***.***:/usr/src/numactl# echo $PKG_CONFIG_PATH
/usr/local/lib64/pkgconfig:/usr/local/share/pkgconfig:/usr/lib64/pkgconfig:/usr/share/pkgconfig

***@***.***:/usr/src/numactl# make
make  all-am
make[1]: Entering directory '/usr/src/numactl'
   CC       numactl.o
   CC       util.o
   CC       shm.o
   CC       libnuma.lo
   CC       syscall.lo
   CC       distance.lo
   CC       affinity.lo
   CC       sysfs.lo
   CC       rtnetlink.lo
   CCLD     libnuma.la
ar: `u' modifier ignored since `D' is the default (see `U')
   CCLD     numactl
   CC       numastat-numastat.o
   CCLD     numastat
   CC       numademo-numademo.o
   CC       numademo-stream_lib.o
   CC       numademo-mt.o
   CC       numademo-clearcache.o
clearcache.c: In function ‘clearcache’:
clearcache.c:74:2: warning: #warning "Consider adding a clearcache 
implementation for your architecture" [-Wcpp]
    74 | #warning "Consider adding a clearcache implementation for your 
architecture"
       |  ^~~~~~~
   CC       numademo-util.o
   CCLD     numademo
   CC       migratepages.o
   CCLD     migratepages
   CC       migspeed.o
   CCLD     migspeed
   CC       memhog.o
   CCLD     memhog
   GEN      numa.pc
make[1]: Leaving directory '/usr/src/numactl'


***@***.***:/usr/src/numactl# make install
make[1]: Entering directory '/usr/src/numactl'
  /usr/bin/mkdir -p '/usr/local/lib'
  /bin/sh ./libtool   --mode=install /usr/bin/ginstall -c   libnuma.la 
'/usr/local/lib'
libtool: install: /usr/bin/ginstall -c .libs/libnuma.so.1.0.0 
/usr/local/lib/libnuma.so.1.0.0
libtool: install: (cd /usr/local/lib && { ln -s -f libnuma.so.1.0.0 
libnuma.so.1 || { rm -f libnuma.so.1 && ln -s libnuma.so.1.0.0 
libnuma.so.1; }; })
libtool: install: (cd /usr/local/lib && { ln -s -f libnuma.so.1.0.0 
libnuma.so || { rm -f libnuma.so && ln -s libnuma.so.1.0.0 libnuma.so; 
}; })
libtool: install: /usr/bin/ginstall -c .libs/libnuma.lai 
/usr/local/lib/libnuma.la
libtool: install: /usr/bin/ginstall -c .libs/libnuma.a 
/usr/local/lib/libnuma.a
libtool: install: chmod 644 /usr/local/lib/libnuma.a
libtool: install: ranlib /usr/local/lib/libnuma.a
libtool: finish: 
PATH="/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/games:/usr/lib64/libexec/kf5:/usr/lib64/qt5/bin:/sbin" 
ldconfig -n /usr/local/lib
----------------------------------------------------------------------
Libraries have been installed in:
    /usr/local/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
    - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
      during execution
    - add LIBDIR to the 'LD_RUN_PATH' environment variable
      during linking
    - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
    - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
  /usr/bin/mkdir -p '/usr/local/bin'
   /bin/sh ./libtool   --mode=install /usr/bin/ginstall -c numactl 
numastat numademo migratepages migspeed memhog '/usr/local/bin'
libtool: install: /usr/bin/ginstall -c .libs/numactl 
/usr/local/bin/numactl
libtool: install: /usr/bin/ginstall -c numastat /usr/local/bin/numastat
libtool: install: /usr/bin/ginstall -c .libs/numademo 
/usr/local/bin/numademo
libtool: install: /usr/bin/ginstall -c .libs/migratepages 
/usr/local/bin/migratepages
libtool: install: /usr/bin/ginstall -c .libs/migspeed 
/usr/local/bin/migspeed
libtool: install: /usr/bin/ginstall -c .libs/memhog 
/usr/local/bin/memhog
  /usr/bin/mkdir -p '/usr/local/include'
  /usr/bin/ginstall -c -m 644 numa.h numacompat1.h numaif.h 
'/usr/local/include'
  /usr/bin/mkdir -p '/usr/local/share/man/man2'
  /usr/bin/ginstall -c -m 644 move_pages.2 '/usr/local/share/man/man2'
  /usr/bin/mkdir -p '/usr/local/share/man/man3'
  /usr/bin/ginstall -c -m 644 numa.3 '/usr/local/share/man/man3'
  /usr/bin/mkdir -p '/usr/local/share/man/man8'
  /usr/bin/ginstall -c -m 644 numactl.8 numastat.8 migratepages.8 
migspeed.8 memhog.8 '/usr/local/share/man/man8'
  /usr/bin/mkdir -p '/usr/local/lib/pkgconfig'
  /usr/bin/ginstall -c -m 644 numa.pc '/usr/local/lib/pkgconfig'
make[1]: Leaving directory '/usr/src/numactl'

***@***.***:/usr/src/numactl# updatedb

***@***.***:/usr/src/numactl# locate numa.pc
/usr/local/lib/pkgconfig/numa.pc
/usr/src/done/numactl/numa.pc
/usr/src/done/numactl/numa.pc.in
/usr/src/numactl/numa.pc
/usr/src/numactl/numa.pc.in






The new file is in the exact same place as the prior one:
/usr/local/lib/pkgconfig/numa.pc

The output in make install, confirms that:   /usr/bin/ginstall -c -m 644 
numa.pc '/usr/local/lib/pkgconfig'

***@***.***:/usr/src/numactl# date
Fri Feb 25 11:49:22 PST 2022

***@***.***:/usr/src/numactl# ls -al /usr/local/lib/pkgconfig/numa.pc
-rw-r--r-- 1 root root 227 Feb 25 11:48 /usr/local/lib/pkgconfig/numa.pc

**Comment by zwt-by** [comment]
@andikleen @Sir-Ace-git   I didn’t know how to fix it, so I downloaded version-2.0.10. It has been working well for me. However, the problem has been resolved in the latest version. So I'll update it to the newer one, thank you!
