### ISSUE TITLE
Project website and ftp not reachable

### ISSUE THREAD

**Issue by SethosII** [numactl/numactl#14]
It looks like the project website and the ftp server are down: http://oss.sgi.com/projects/libnuma/ and ftp://oss.sgi.com/www/projects/libnuma/download/.

**Comment by filbranden** [comment]
@cpwickman is there a replacement location for the downloads?

Should we use GitHub for that?

**Comment by cpwickman** [comment]
Hi Filipe,

I am not at SGI/HPE anymore, but I see that they have taken down oss.sgi.com.
I asked a manager back there if there was to be a replacement but I take it
from his non-reply that there will not be one.  So I think you should use
github.

I still get copied on the occasional patch to libnuma/numact.  But I'm not
familiar with using github so I have left it to you to integrate and test.
I'm not 'resigning', but I don't think I can be of much help so that's
about the same thing. Let me know if there is something I can do.

-Cliff

**Comment by filbranden** [comment]
Yeah that's fine, let me look at starting to use GitHub to host the versions...

I wonder if we still have tarballs for the past releases... Any chance you might have a "mirror" of that old directory?

Cheers,
Filipe

**Comment by cpwickman** [comment]
Hi Filipe,

I don't have any backups of oss.sgi.com.
I will ask a manager at SGI/HPE if he can find any backups.

-Cliff
