### ISSUE TITLE
numactl -N fails for nodes with no memory

### ISSUE THREAD

**Issue by tavianator** [numactl/numactl#165]
I have a Threadripper 3960X in NPS4 configuration, which looks like this:

```console
tavianator@tachyon $ numactl -H
available: 4 nodes (0-3)
node 0 cpus: 0 1 2 3 4 5 24 25 26 27 28 29
node 0 size: 0 MB
node 0 free: 0 MB
node 1 cpus: 6 7 8 9 10 11 30 31 32 33 34 35
node 1 size: 64307 MB
node 1 free: 19214 MB
node 2 cpus: 12 13 14 15 16 17 36 37 38 39 40 41
node 2 size: 64472 MB
node 2 free: 27945 MB
node 3 cpus: 18 19 20 21 22 23 42 43 44 45 46 47
node 3 size: 0 MB
node 3 free: 0 MB
node distances:
node   0   1   2   3 
  0:  10  12  12  12 
  1:  12  10  12  12 
  2:  12  12  10  12 
  3:  12  12  12  10 
```

Nodes 0 and 3 have CPUs but no memory attached.  So it makes sense that I can't do `numactl -m 0`, but `numactl -N 0` also fails:

```console
tavianator@tachyon $ numactl -N 0 -- numactl -s
libnuma: Warning: node argument 0 is out of range

<0> is invalid
usage: numactl [--all | -a] [--balancing | -b] [--interleave= | -i <nodes>]
...
```

I don't see why setting CPU affinity to those nodes should fail.  `-C` works:

```console
tavianator@tachyon $ numactl -C 0-5,24-29 -- numactl -s
policy: default
preferred node: current
physcpubind: 0 1 2 3 4 5 24 25 26 27 28 29 
cpubind: 
nodebind: 
membind: 1 2 
preferred: 
```

**Comment by luochenglcs** [comment]
This issue is the same as the previous issue https://github.com/numactl/numactl/issues/127.

I think it is because there is no memory available on node0 and node3, the numa_init->set_task_constraints function gets the available node through /proc/self/status, and there is no node0 and node3 in it, so node0 and node3 is not in the available range, which is reasonable.

you can try  to use "numactl -a -N 0".

**Comment by andikleen** [comment]
Should be fixed now.
