### ISSUE TITLE
Missing changelog

### ISSUE THREAD

**Issue by f18m** [numactl/numactl#60]
Hi,
I cannot find any changelog for the libnuma... I am using an older version and I wonder what's changed and what I should change in my program if I upgrade...

Thanks

**Comment by andikleen** [comment]
On Tue, Jan 29, 2019 at 01:49:18AM -0800, Francesco Montorsi wrote:
> Hi,
> I cannot find any changelog for the libnuma... I am using an older version and
> I wonder what's changed and what I should change in my program if I upgrade...

The changelog is in git.

libnuma is fully binary compatible, so likely nothing.

-Andi

**Comment by f18m** [comment]
Ok, thanks... when you say the changelog is in git, you mean that the git history should be used as reference (but that does not specify which changes were done in which release) or rather that there is some file I missed containing a standard ChangeLog?

Thanks

**Comment by filbranden** [comment]
Yes, you can browse the Git history to see what changed.

Either here, from GitHub: https://github.com/numactl/numactl/commits/master

Or use `git log` and similar tools if you have a git checkout.

We don't otherwise maintain a Changelog file here.

I'll close this issue, since I believe this has been answered.
