### ISSUE TITLE
libnuma: Warning: node argument 1 is out of range

### ISSUE THREAD

**Issue by zingdle** [numactl/numactl#67]
```
$ numactl --hardware
available: 2 nodes (0-1)
node 0 cpus: 0 2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70
node 0 size: 128702 MB
node 0 free: 85302 MB
node 1 cpus: 1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67 69 71
node 1 size: 0 MB
node 1 free: 0 MB
node distances:
node   0   1
  0:  10  20
  1:  20  10
```

```
$ numactl --cpunodebind=1 ./a.out
libnuma: Warning: node argument 1 is out of range
...
```
There are 36 cpus on node 1 but I fail to bind it. I believe it's reasonable though there's no memory attaching on it.

Also, I noticed that using `--membind=0` explicitly greatly reduce minor page faults. What could possibly cause this?

**Comment by redno2** [comment]
this bug affected to me to, on a isolate cpu.

$ cat /proc/cmdline 
BOOT_IMAGE=/@/boot/vmlinuz-5.3.0-46-generic root=UUID=bfee8f8c-7f3f-4ee4-9d9e-7af5becf0bd1 ro rootflags=subvol=@ nomodeset quiet splash isolcpus=6,7 nmi_watchdog=0 idle=poll nohz_full=6,7 rcu_nocbs=6,7 processor.max_cstate=1 intel_pstate=disable nohz=on nosoftlockup skew_tick=1 vt.handoff=7


$ cat /proc/cpuinfo | grep proc
processor       : 0
processor       : 1
processor       : 2
processor       : 3
processor       : 4
processor       : 5
processor       : 6
processor       : 7


$ numactl --hardware
available: 1 nodes (0)
node 0 cpus: 0 1 2 3 4 5 6 7
node 0 size: 15954 MB
node 0 free: 12139 MB
node distances:
node   0 
  0:  10 

  
$ touch /tmp/bob
$ numactl --physcpubind 5 ls /tmp/bob 
/tmp/bob
$ numactl --physcpubind 6 ls /tmp/bob 
libnuma: Warning: cpu argument 6 is out of range

<6> is invalid
usage: numactl [--all | -a] [--interleave= | -i <nodes>] [--preferred= | -p <node>]
               [--physcpubind= | -C <cpus>] [--cpunodebind= | -N <nodes>]
               [--membind= | -m <nodes>] [--localalloc | -l] command args ...
       numactl [--show | -s]
       numactl [--hardware | -H]
       numactl [--length | -l <length>] [--offset | -o <offset>] [--shmmode | -M <shmmode>]
               [--strict | -t]
               [--shmid | -I <id>] --shm | -S <shmkeyfile>
               [--shmid | -I <id>] --file | -f <tmpfsfile>
               [--huge | -u] [--touch | -T] 
               memory policy | --dump | -d | --dump-nodes | -D

memory policy is --interleave | -i, --preferred | -p, --membind | -m, --localalloc | -l
<nodes> is a comma delimited list of node numbers or A-B ranges or all.
Instead of a number a node can also be:
  netdev:DEV the node connected to network device DEV
  file:PATH  the node the block device of path is connected to
  ip:HOST    the node of the network device host routes through
  block:PATH the node of block device path
  pci:[seg:]bus:dev[:func] The node of a PCI device
<cpus> is a comma delimited list of cpu numbers or A-B ranges or all
all ranges can be inverted with !
all numbers and ranges can be made cpuset-relative with +
the old --cpubind argument is deprecated.
use --cpunodebind or --physcpubind instead
<length> can have g (GB), m (MB) or k (KB) suffixes




$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 19.10
Release:        19.10
Codename:       eoan

**Comment by vahid83** [comment]
I am having the same issue, is there any solution for this?

**Comment by zingdle** [comment]
> There are 36 cpus on node 1 but I fail to bind it. I believe it's reasonable though there's no memory attaching on it.

Should use `--physcpubind=cpus, -C cpus` instead.

**Comment by xbreak** [comment]
Add `--all` to consider all cpus, not just current cpuset (which excludes isolated cpus).

```console
$ numactl -C 16 -- echo ok
libnuma: Warning: cpu argument 16 is out of range
$ numactl --all -C 16 -- echo ok
ok
```
